import type { NextPage } from 'next';
import Head from 'next/head';

import 'tailwindcss/tailwind.css';
import Card from '../components/card';

const Home: NextPage = () => {
  const p1 = (
    <>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
    </>
  );

  const p2 = (
    <>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <div className="border-4 border-black border-dashed rounded-lg aspect-[1/1.5]"></div>
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
    </>
  );

  const h = (
    <>
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
      <Card name="rayan gosling" health={10} armor={4} />
    </>
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen text-center overflow-hidden mx-auto bg-haikei-bauhaus bg-no-repeat bg-cover">
        <div className='inline-grid grid-rows-12 gap-y-4'></div>
        <div className="row-span-2 row-start-1 row-end-3">
          <div className="max-w-screen-xl mx-auto shadow-lg shadow-black rounded-xl bg-gray-200 text-gray-900 text-3xl">
            <div className="inline-grid grid-cols-9 gap-2 h-full w-full mx-auto p-3">{h}</div>
          </div>
        </div>
        <div className="row-span-8 row-start-4">
          <div className="p-2 max-w-screen-2xl mx-auto shadow-lg shadow-black rounded-xl bg-gray-200 text-gray-900 text-3xl">
            <div className="inline-grid grid-rows-2 gap-2 h-full w-full mx-auto">
              <div className="inline-grid grid-rows-2 gap-2 h-full w-full mx-auto p-3">
                <div className="inline-grid grid-cols-9 gap-2 h-full w-full mx-auto p-3">{p1}</div>
              </div>
              <div className="inline-grid grid-rows-2 gap-2 h-full w-full mx-auto p-3">
                <div className="inline-grid grid-cols-9 gap-2 h-full w-full mx-auto p-3">{p2}</div>
              </div>
            </div>
          </div>
        </div>
        <div className="row-span-2">
          <div className="max-w-screen-xl mx-auto shadow-lg shadow-black rounded-xl bg-gray-200 text-gray-900 text-3xl">
            <div className="inline-grid grid-cols-9 gap-2 h-full w-full mx-auto p-3">{h}</div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
